# Generated by Django 2.2.11 on 2020-03-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiket_adi', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='boyaci',
            name='boyaci_etiket',
            field=models.ManyToManyField(related_name='boyacilar', to='boya.Etiket'),
        ),
    ]
