# Generated by Django 2.2.11 on 2020-03-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorcDefteri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borclu_isim', models.CharField(max_length=100, verbose_name='Borçlu İsmi')),
                ('borclu_telefon', models.CharField(max_length=11, verbose_name='Telefon')),
                ('borclu_aciklama', models.TextField(verbose_name='Açıklama')),
                ('borc_baslangic', models.DateTimeField(auto_now_add=True)),
                ('borc_son_odeme', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='boyaci',
            options={'verbose_name': 'Boyacı', 'verbose_name_plural': 'Boyacılar'},
        ),
        migrations.AlterModelOptions(
            name='etiket',
            options={'verbose_name': 'Etiket', 'verbose_name_plural': 'Etiketler'},
        ),
        migrations.AlterModelOptions(
            name='verilenis',
            options={'verbose_name': 'Verilen İş', 'verbose_name_plural': 'Verilen İşler'},
        ),
        migrations.AlterField(
            model_name='verilenis',
            name='is_aciklama',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='verilenis',
            name='is_alan_boyaci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verilen_isler', to='boya.Boyaci', verbose_name='Boyacı'),
        ),
        migrations.AlterField(
            model_name='verilenis',
            name='is_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='İş Alma Tarihi'),
        ),
    ]
