# Generated by Django 2.2.11 on 2020-03-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boya', '0002_auto_20200314_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_aciklama', models.TextField(verbose_name='Not Açıklaması')),
                ('yapildi_mi', models.BooleanField(default=False, verbose_name='Not Durumu')),
            ],
            options={
                'verbose_name': 'Not',
                'verbose_name_plural': 'Notlar',
            },
        ),
        migrations.AlterModelOptions(
            name='borcdefteri',
            options={'verbose_name': 'Borç Defteri', 'verbose_name_plural': 'Borç Defteri'},
        ),
        migrations.AlterField(
            model_name='borcdefteri',
            name='borc_son_odeme',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Tarihi'),
        ),
    ]
