# Generated by Django 2.2.11 on 2020-03-14 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boya', '0003_auto_20200314_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='notlar',
            name='not_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notlar',
            name='yapildi_mi',
            field=models.BooleanField(default=False, verbose_name='Yapıldı mı'),
        ),
    ]
