# Generated by Django 2.2.11 on 2020-03-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boya', '0004_auto_20200314_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notlar',
            name='not_aciklama',
            field=models.CharField(max_length=200, verbose_name='Not Açıklaması'),
        ),
    ]
